### ISSUE TITLE
Некорректное сохранение позиции миникарты в персистивном режиме

### ISSUE THREAD

**Issue by PolarWooolf** [OnlyNoob/Metrostroi-MiniMap#7]
При переводе карты в персистивный режим после первой перезагрузки появляется на ~ 2 метра выше.

**Comment by PolarWooolf** [comment]
Выглядит это так:

![2015-09-28_00001](https://cloud.githubusercontent.com/assets/3987278/10127082/7cac5f6c-65be-11e5-8dbe-ce69bd30f648.jpg)

**Comment by OnlyNoob** [comment]
Что у тебя в файле 'addons/Minimap/lua/autorun/server/metrostroi_minimap_util.lua' на строке 26?

**Comment by PolarWooolf** [comment]
```
        minimap:SetPos(v.Pos - Vector(0,0,140))
```

**Comment by OnlyNoob** [comment]
Должно все верно появляться. Эта строка и должна опустить карту при спавне. Возможно ты сохранили миникарту сторонними плагинами. Используй встроенное сохранение ([Команды миникарты](https://github.com/OnlyNoob/Metrostroi-MiniMap/wiki/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%8B))

**Comment by PolarWooolf** [comment]
Значит, таки что-то не так :) Перепроверь у себя
.

**Comment by PolarWooolf** [comment]
Перепроверил - сдвигается при каждой корректной перезагрузке.

**Comment by OnlyNoob** [comment]
Проверял у меня все нормально, ты уверен что используешь metrostroi_minimap_save? Все сохраняется и опускается корректно, а вот если использовать какойто сторонний плагин сохранения то она будет так же летать.

**Comment by PolarWooolf** [comment]
Стоооп. Нужно эту команду исполнять? Я просто персистил её...

28.09.2015, 22:51, "OnlyNoob" notifications@github.com:

**Comment by OnlyNoob** [comment]
Я обновил комент выше.

**Comment by PolarWooolf** [comment]
Отлично, спасибо, разобрался.
